version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "20:45"
      timezone: "Asia/Tokyo"
    target-branch: "target-branch-test"
    allow:
      - dependency-name: "requests"